version: '3.9'
services:
  api-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: bikeramp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: api-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: bikeramp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      MAP_BASE_URL: https://api.mapbox.com
      MAP_TOKEN: pk.eyJ1IjoiZnVyeWludGhlZmFpciIsImEiOiJjbDVqZDZjODUwZHUzM2pwejRhM245OWcyIn0.sO3z8J203mhuwgme3qW4Jw
      DB_TYPE: postgres
    depends_on:
      - api-db